import Image from "next/image";

export default function Page() {
  return (
    <>
      <h1>Next.js Vercel Discord Stripe Subscribers Target Bot</h1>
      <p>
        The script that posts is in{" "}
        <code>app/api/cron/daily-discord-message/route.ts</code>, this script is
        run daily at 9am, this is configured in <code>vercel.json</code>. The
        message contains a link to an image, which is generated by{" "}
        <code>/api/images/graph/[fileName]/route.tsx</code>, visible below.
      </p>
      <Image
        alt="graph"
        src="/api/images/graph/graph.gif?start=50&startDate=2024-01-05T00%3A00%3A00.000Z&current=51&currentDate=2024-01-11T16%3A49%3A18.774Z&goal=100&goalDate=2024-02-05T00%3A00%3A00.000Z&daysTotal=31&dailyGoal=2&daysGone=6&expectedCurrent=62&daysRemaining=24&newDailyGoal=2"
        width={500}
        height={250}
      />
    </>
  );
}
